[tool.poetry]
name = "project-otto"
version = "0.1.0"
description = "The new 2021-2022 auto-aim vision system."
authors = ["Advanced Robotics at the University of Washington <robomstr@uw.edu>"]
include = ["project_otto/py.typed"]

[[tool.poetry.source]]
name = "aruw_pypi"
url = "https://gitlab.com/api/v4/groups/9205524/-/packages/pypi/simple"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
# transforms3d hasn't published a release since 2017, but is still intermittently maintained on GitHub
transforms3d = { git = "https://github.com/matthew-brett/transforms3d.git" }
numpy = "1.24.1"
lightning_models = { path = "./aruw-lightning-models/", develop = true }
pyserial = "^3.5"
bitstruct = "^8.12.1"
PyYAML = "^6.0"
# headless due to: https://gitlab.com/aruw/vision/project-otto/-/issues/76
# contrib for ArUco markers used in spatial calibration
opencv-contrib-python-headless = { version = "^4.11", python = "^3.10" }
# We host our own Jetson wheel that is built with CUDA support
# We also need to explicitly download the CPU-only version of pytorch, otherwise GitLab CI fails (https://github.com/pytorch/pytorch/issues/89417)
torch = [
    {markers="platform_system == \"Linux\" and platform_machine == \"aarch64\"", url="https://developer.download.nvidia.com/compute/redist/jp/v61/pytorch/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl"},
    {version="2.1.0", markers="platform_system == \"Linux\" and platform_machine != \"aarch64\"", source='pytorch_cpu'},
    {version="2.1.0", markers="platform_system != \"Linux\"", source='pypi'}
]
# pyrealsense2 only has official builds on PyPI for x86. On other platforms (Jetson, Apple
# Silicon), we have to manually compile and install a wheel if we want the package.
# pyrealsense2 is unused in our tests and only required for full-system operation.
pyrealsense2 = { version = "2.50.0.*", optional = true, source = "aruw_pypi" }
pyusb = "^1.2.1"
# PyGObject is only officially supported on Windows via mysys2.
PyGObject = { version = "^3.42.1", optional = true }
mergedeep = "^1.3.4"
numpy-quaternion = "^2022.4.2"
cpp_serial = { version = "1.1.1", source = "aruw_pypi" }
aruw-pathfinding = {version = "^0.8.10", source = "aruw_pypi"}
jetson-gpio = { version = "^2.1.1", optional = true }
scipy = "^1.15.2"
aiortc = "^1.11.0"
python-json-logger = "^4.0.0"
av = "14.0.0"
robomaster-particle-filters = [
    {version="1.0.7", source = "aruw_pypi", optional = true, markers='platform_system == "Linux" and platform_machine == "aarch64"'},
    {version="1.0.7", source = "aruw_pypi", optional = true, markers='platform_system == "Darwin" and platform_machine == "arm64"'}
]

[tool.poetry.dev-dependencies]
# test
pytest = "^6.2.4"
pytest-snapshot = "^0.6.1"
Pillow = "^9.0.1"

# linting
flakehell = "^0.9.0"
pep8-naming = "^0.12.0"
flake8-use-fstring = "^1.1"
flake8-docstrings = "^1.6.0"
flake8-isort = "^4.0.0"
flake8-black = "^0.3.3"
flake8-bugbear = "^21.4.3"
flake8 = "3.9.2"

# docs gen
Sphinx = "^4.5.0"
sphinx-rtd-theme = "^0.5.2"
sphinx-autodoc-typehints = "=1.12.0"
myst-parser = { version = "^0.15.2", extras = ["linkify"] }
sphinxcontrib-mermaid = "^0.7.1"
sphinxcontrib-youtube = "^1.0.1"

# profiling
# Version 3.4.0 was found to be compatible with Apple's Rosetta 2 on M1 Macs, while newer versions were not.
line-profiler = {version="3.4.0", optional=true}

[tool.poetry.extras]
# Optional dependencies to install on the jetson
jetson = ["PyGObject", "line-profiler", "jetson-gpio", "pyrealsense2", "robomaster-particle-filters"]

[tool.flakehell]
exclude = [
    "README.md",
    # CI keeps venv within project, so must be ignored for linting
    ".venv",
    ".cache",
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".vscode",
    # flakehell defaults to linting code snippets in docs, but it doesn't handle all MyST features
    # and we have few fully-defined code snippets.
    "*.md",
    "*.rst",
    "node_modules",
    "aruw-lightning-models",
]
format = "colored"
# Note: line length is also specified in tasks.py and other tools below
max_line_length = 100
show_source = true
extended_default_ignore = []

[tool.flakehell.plugins]
pyflakes = ["+*"]
pycodestyle = [
    "+*",
    "-W503", # disable "line break before binary operator": no longer part of PEP8
    "-E203", # disable "whitespace before ':'": conflicts with PEP8
]
pep8-naming = ["+*"]
"flake8-*" = ["+*"]
"flake8-docstrings" = [
    "+*",
    "-D107", # disable "Missing docstring in __init__": we want to consolidate class-level and __init__-level docstrings
    "-D200", # disable "One-line docstring should fit on one line with quotes": does not understand line length limitation
    "-D401", # disable "First line should be in imperative mood; try rephrasing": broken for properties, see https://github.com/PyCQA/pydocstyle/issues/531
    "-D402", # disable "First line should not be the function's "signature"": good signatures document as well as any hundred-char docstring
]

[tool.flakehell.exceptions."tests/"]
flake8-docstrings = ["-*"]

[tool.flakehell.exceptions."tools/"]
flake8-docstrings = ["-*"]

[tool.flakehell.exceptions."deployment/"]
flake8-docstrings = ["-*"]

[tool.flakehell.exceptions."tasks.py"]
flake8-docstrings = ["-*"]

[tool.flakehell.exceptions."docs/conf.py"]
flake8-docstrings = ["-*"]

[tool.isort]
skip = [".venv", ".cache", ".git", ".pytest_cache", "node_modules", "aruw-lightning-models"]
profile = "black"
line_length = 100
multi_line_output = 3

[tool.black]
line-length = 100
extend-exclude = '''
aruw-lightning-models
'''

[tool.poetry.scripts]
##### Development tasks #####
# correctness tasks
test                  = "tasks:test"
ui-test               = "tasks:ui_test"
lightning-model-test  = "tasks:lightning_model_test"
update-snapshots      = "tasks:update_snapshots"
typecheck             = "tasks:typecheck"
check-lock            = "tasks:check_lock"
# policy tasks
lint                  = "tasks:lint"
format                = "tasks:format"
# docs tasks
gen-docs              = "tasks:gen_docs"
serve-docs            = "tasks:serve_docs"
clean-docs            = "tasks:clean_docs"
# misc util tasks
relock                = "tasks:relock"
check                 = "tasks:check"
get-lightning-weights = "tasks:get_lightning_weights"

##### System operation tools #####
uart-terminal             = "tools.uart_terminal:main"
k-means-demo              = "tools.k_means_demo:main"
main                      = "project_otto.main:main"
main_default              = "tasks:main_default"

[tool.pyright]
exclude = [
    ".venv",
    "node_modules",
    "aruw-lightning-models/"
]
pythonVersion = "3.10"
typeCheckingMode  = "strict"
# below make it difficult to interact with external libraries like numpy
# TODO: evaluate re-enabling some or all of them
reportUnknownParameterType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
# variables have been easy to type and provide good checking for transform library
reportUnknownVariableType = true
reportUnknownMemberType = false
reportIncompleteStub = false

reportImplicitStringConcatenation = "error"
reportUnusedCallResult = "warning"
reportMissingTypeArgument = "warning"

reportUnusedVariable = "warning"
reportUnusedFunction = "warning"
reportUnusedClass = "warning"
reportUnusedImport = "warning"

[tool.pytest.ini_options]
markers = [
    "ui_test: tests checking code behavior under the Pyright type-checker, which require Pyright to be installed globally",
    "lightning_model_test: tests checking code whose functionality depends on running a PyTorch model",
]
norecursedirs = "aruw-lightning-models"
testpaths = "tests"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
