from typing import List
import numpy as np
import numpy.typing as npt

class ObservedPlate:
    def __init__(self, position: npt.NDArray[np.float32],
                 position_diagonal_covariance: npt.NDArray[np.float32]): ...

    def position(self) -> npt.NDArray[np.float32]: ...
    def position_diagonal_covariance(self) -> npt.NDArray[np.float32]: ...

class PredictedPlate:
    def __init__(
        self, position: npt.NDArray[np.float32], velocity: npt.NDArray[np.float32]): ...

    def position(self) -> npt.NDArray[np.float32]: ...
    def velocity(self) -> npt.NDArray[np.float32]: ...

class Observation:
    @staticmethod
    def from_one_plate(observer_position: npt.NDArray[np.float32],
                       plate_one: ObservedPlate) -> Observation: ...

    @staticmethod
    def from_two_plates(observer_position: npt.NDArray[np.float32], plate_one: ObservedPlate,
                        plate_two: ObservedPlate) -> Observation: ...

class Prediction:
    def predicted_plates(self) -> List[PredictedPlate]: ...
    def radius(self) -> float: ...
    def z_coordinate_0(self) -> float: ...
    def z_coordinate_1(self) -> float: ...
    def orientation(self) -> float: ...
    def orientation_velocity(self) -> float: ...
    def center(self) -> npt.NDArray[np.float32]: ...
    def center_velocity(self) -> npt.NDArray[np.float32]: ...
    def extrapolate_state(
        self, time_offset_seconds: float) -> Prediction: ...

class ParticleFilterConfigurationParameters:
    def __init__(
        self,
        radius_prior: float,
        visibility_logit_coefficient: float,
        radius_prior_variance_one_plate: float,
        radius_prior_variance_two_plates: float,
        radius_process_variance: float,
        z_coordinate_common_process_variance: float,
        z_coordinate_offset_process_variance: float,
        orientation_velocity_prior_variance: float,
        orientation_velocity_process_variance: float,
        center_velocity_prior_diagonal_covariance: npt.NDArray[np.float32],
        center_velocity_process_diagonal_covariance: npt.NDArray[np.float32]): ...

class ParticleFilter:
    def __init__(self, number_of_samples: int, initial_observation: Observation,
                 params: ParticleFilterConfigurationParameters): ...

    def extrapolate_state(
        self, time_offset_seconds: float) -> Prediction: ...

    def update_state_sans_observation(self, time_offset_seconds: float) -> None: ...

    def update_state_with_observation(
        self, time_offset_seconds: float, state: Observation) -> None: ...

    def reinitialize(self, observation: Observation) -> None: ...